name: compression
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - cudatoolkit=11.3
  - pytorch-lightning=1.6
  - fairscale
  - scipy
  - yaml
  - matplotlib
  - pip:
    - gif
