name: compression
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - cudatoolkit=11.3
  - pytorch-lightning
  - fairscale
  - scipy
  - yaml
  - matplotlib
  - pip
  - pip:
    - gif
    - deepspeed
