name: compression
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
  - pytorch-lightning=1.6
  - scipy
  - yaml
