name: QuadConv
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - cudatoolkit
  - pytorch-lightning
  - pytorch-scatter
  - pytorch-geometric
  - pytorch-cluster
  - scipy
  - yaml
  - matplotlib
  - pip
  - pip:
    - gif
    - torch_tb_profiler
